name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install diff

      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Run the Application
        run: javac Main/Main.java; java Main/Main
      - name: lint with checkstyle
        run: java -jar google-java-format-1.18.1-all-deps.jar Main/Main.java > main_formatted.java
      - run: diff Main/Main.java main_formatted.java > main_diff.txt
      - run: java -jar google-java-format-1.18.1-all-deps.jar Tester/Main.java > tester_formatted.java
      - run: diff Tester/Main.java tester_formatted.java > tester_diff.txt
      - run: if [ "$(wc main_diff.java)" -gt 2]; then echo "FAIL"; else echo "PASS"; fi
      - run: if [ "$(wc tester_diff.java)" -gt 2]; then echo "FAIL"; else echo "PASS"; fi
      - name: Run the Tester
        run: javac Tester/Main.java; java Tester/Main
      - name: Push the binaries to the repo
        run: |
          git config --global user.email "kadirgokhann@gmail.com"
          git config --global user.name "kadirgokhann"
          git add . && git commit -m "add binary" && git push
