name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "31 2 * * 1"
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your basdasdranchs is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

  linting:
    name: Lint Code Base
    needs: info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVA: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_test:
    runs-on: ubuntu-latest
    needs: [info, linting]
    steps:
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run the Application
        run: javac main/Mainfunction.java; java main/Mainfunction
      - name: Run the Tester
        id: test_id
        run: javac tester/Maintester.java; java tester/Maintester
      - name: Push the binaries to the repo
        run: |
          git config --global user.email "kadirgokhann@gmail.com"
          git config --global user.name "kadirgokhann"
          git add . && git commit -m "add binary" && git push
  codeql_analyze:
    name: CodeQL Analyze
    needs: [info, linting, build_test]
    runs-on: "ubuntu-latest"
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["java-kotlin"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Run the Application
        run: javac main/Mainfunction.java; java main/Mainfunction
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
